name: SYNC WITH falcoeye Github
'on':
  push:
    branches:
      - main
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "sourcya/falcoeye-user-app"
          source_branch: "main"
          destination_branch: "main"
          destination_repo: ${{secrets.GITLAB_ACCESS}}
          source_ssh_private_key: ${{ secrets.ZAZAN_SSH_PRIVATE_KEY }}
